[build]
builder = "nixpacks"
buildCommand = "chmod +x node_modules/.bin/prisma && node_modules/.bin/prisma generate --schema=packages/database/prisma/schema.prisma && pnpm --filter @flowtiq/api build"

[deploy]
startCommand = "node_modules/.bin/prisma db push --schema=packages/database/prisma/schema.prisma --accept-data-loss && node services/api/dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
  [environments.production.deploy]
  startCommand = "node_modules/.bin/prisma db push --schema=packages/database/prisma/schema.prisma --accept-data-loss && node services/api/dist/index.js"
